config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "pages/help", to: "pages#help"
  get "/pages/:page", to: "pages#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    resources :book_borrows, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end
  resources :books
  resources :authors, only: :show
  resources :relationships, only: [:create, :destroy]

  namespace :admin do
    root "book_borrows#index"
    resources :users
    resources :authors
    resources :books
    resources :publishers
    resources :categories
    resources :book_borrows, only: [:index, :update, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_one :book_borrow
  has_many :users, through: :book_borrows
  belongs_to :author
  belongs_to :publisher
  belongs_to :category
  mount_uploader :image, PictureUploader
  validates :name, presence: true,
    length: {maximum: Settings.name.maximum},
    uniqueness: {scope: :author_id}
  validates :paperback, presence: true
  validate  :picture_size

  delegate :name, to: :author, prefix: true
  delegate :name, to: :category, prefix: true
  delegate :name, to: :publisher, prefix: true
  scope :search, ->q{where "name LIKE ?", "%#{q}%"}

  private

  def picture_size
    if image.size > 1.megabytes
      errors.add(:image, I18n.t(".less_than"))
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :load_author_publisher_category,
    except: [:show, :destroy, :index]
  before_action :load_book, except: [:index, :new, :create]
  layout "admin"

  def index
    if params[:active_search]
      @books = Book.includes(:publisher, :author, :category)
        .select(:id, :name, :author_id, :publisher_id, :category_id)
        .search(params[:name]).order(name: :asc).paginate page: params[:page],
        per_page: Settings.paginate.per_page

      render json: {
        html_search: render_to_string(@books),
      }, status: :ok
    else
      @books = Book.includes(:publisher, :author, :category)
        .select(:id, :name, :author_id, :publisher_id, :category_id)
        .order(id: :asc).paginate page: params[:page],
        per_page: Settings.paginate.per_page
    end
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = t ".book"
      redirect_to admin_books_url
    else
      render :new
    end
  end

  def update
    if @book.update_attributes book_params
      flash[:success] = t ".success"
      redirect_to admin_books_url
    else
      render :edit
    end
  end

  def destroy
    if @book.destroy
      flash[:success] = t ".delete"
    else
      flash[:danger] = t ".delete_fail"
    end
    redirect_to admin_books_url
  end

  private

  def book_params
    params.require(:book).permit :name, :author_id, :image,
      :paperback, :publisher_id, :category_id
  end

  def load_author_publisher_category
    @author = Author.all.map{|c| [c.name, c.id]}
    @publisher = Publisher.all.map{|a| [a.name, a.id]}
    @category = Category.all.map{|b| [b.name, b.id]}
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_book, only: :show

  def show
  end

  def index
    @books = Book.all
  end
end

app/views/admin/books/_book.html.erb
<tr>
  <td><%= link_to book.name, admin_book_path(book) %></td>
  <td><%= book.category_name %></td>
  <td><%= book.author_name %></td>
  <td><%= book.publisher_name %></td>
  <td></td>
  <td>
    <div class="btn-group btn-group-sm">
      <%= link_to edit_admin_book_path(book) do %>
        <i class="glyphicon glyphicon-pencil btn btn-warning"
          title="<%= t "edit" %>"></i>
      <% end %>
      <%= link_to admin_book_path(book), method: :delete,
        data: {confirm: t("confirm")} do %>
        <i class="glyphicon glyphicon-trash btn btn-danger"
          title="<%= t "delete" %>"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/admin/books/edit.html.erb
<% provide :title, t(".editbook") %>
<h1 class="text-center"><%= t ".update" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @book] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <div class="form-group">
        <%= f.label :name, t(".name") %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :author %>
        <%= f.select :author_id, @author, {}, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :publisher %>
        <%= f.select :publisher_id, @publisher, {}, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :category %>
        <%= f.select :category_id, @category, {}, class: "form-control" %>
      </div>
      <span class="picture">
        <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
      </span>

      <div class="form-group">
        <%= f.label :paperback, t(".paperback") %>
        <%= f.text_field :paperback, class: "form-control" %>
      </div>

      <%= f.submit t(".update"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/books/index.html.erb
<% provide :title, t(".all_book") %>
<% provide :placeholder, t(".search_book") %>
<h1><%= t ".all_book" %> </h1>

<%= form_for admin_books_path, remote: true, method: :get do %>
  <%= render "shared/search_form" %>
<% end %>

<%= will_paginate %>

<table class="table">
  <thead>
    <tr>
      <th><%= t "name" %></th>
      <th><%= t "category" %></th>
      <th><%= t "author" %></th>
      <th><%= t ".publisher" %></th>
      <th><%= t "status" %></th>
      <th><%= t "action" %></th>
    </tr>
  </thead>
  <tbody class="table-book">
    <%= render @books %>
  </tbody>
</table>

app/views/admin/books/new.html.erb
<% provide :title, t(".create") %>
<h1 class="text-center"><%= t ".create" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @book] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <div class="form-group">
        <%= f.label :name, t(".name") %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :author %>
        <%= f.select :author_id, @author, {}, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :publisher %>
        <%= f.select :publisher_id, @publisher, {}, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :category %>
        <%= f.select :category_id, @category, {}, class: "form-control" %>
      </div>

      <span class="picture">
        <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
      </span>

      <div class="form-group">
        <%= f.label :paperback, t(".paperback") %>
        <%= f.text_field :paperback, class: "form-control" %>
      </div>

      <%= f.submit t(".create"), class: "btn btn-primary form-control" %>
    <% end %>
  </div>
</div>

app/views/admin/books/show.html.erb
<% provide :title, @book.name %>
<div class="row">
  <h1><%= @book.name %></h1>
  <div class="col-md-5">
    <% if @book.image.url %>
      <%= image_tag(@book.image) %>
    <% else %>
      <%= image_tag Settings.default_image, size: Settings.book_size.size %>
    <% end %>
  </div>
</div>
<ul>
  <li><%= @book.author.name %></li>
  <li><%= @book.publisher.name %></li>
  <li><%= @book.category.name %></li>
</ul>