config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "pages/help", to: "pages#help"
  get "/pages/:page", to: "pages#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    resources :book_borrows, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end
  resources :books
  resources :authors, only: :show
  resources :relationships, only: [:create, :destroy]

  namespace :admin do
    root "book_borrows#index"
    resources :users
    resources :authors
    resources :books
    resources :publishers
    resources :categories
    resources :book_borrows, only: [:index, :update, :destroy]
  end
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  validates :name, presence: true, length: {maximum: Settings.name.maximum}
  validates :description, presence: true
  scope :search, ->q{where "name LIKE ?", "%#{q}%"}
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :load_author, except: [:new, :index, :create]
  layout "admin"

  def index
    if params[:q].present?
      @authors = Author.includes(:books).select(:id, :name)
        .search(params[:q]).order(name: :asc).paginate page: params[:page],
        per_page: Settings.paginate.per_page
    else
      @authors = Author.includes(:books).select(:id, :name)
        .order(name: :asc).paginate page: params[:page],
        per_page: Settings.paginate.per_page
    end
  end

  def show
    @books = Book.where(author_id: @author.id)
  end

  def new
    @author = Author.new
  end

  def edit
  end

  def create
    @author = Author.new author_params
    if @author.save
      flash[:success] = t ".author"
      redirect_to admin_authors_url
    else
      render :new
    end
  end

  def update
    if @author.update_attributes author_params
      flash[:success] = t ".success"
      redirect_to admin_author_url
    else
      render :edit
    end
  end

  def destroy
    if @author.books.any?
       flash[:danger] = t ".delete_fail"
    else
      if @author.destroy
        flash[:success] = t ".delete"
      else
        flash[:danger] = t ".delete_fail"
      end
    end
    redirect_to admin_authors_url
  end

  private

  def author_params
    params.require(:author).permit :name, :description
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :load_author

  def show
    @books = Book.where(author_id: @author.id)
  end
end

app/views/admin/authors/edit.html.erb
<% provide :title, t(".editauthor") %>
<h1><%= t ".update" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @author] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, t(".description") %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.submit t(".update"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/authors/index.html.erb
<% provide :title, t(".all_author") %>
<% provide :placeholder, t(".search_author") %>
<h1><%= t ".all_author" %> </h1>

<%= form_for admin_authors_path, method: :get do %>
  <%= render "shared/search_form" %>
<% end %>

<%= will_paginate %>

<table class="table">
  <thead>
    <tr>
      <th><%= t "name" %></th>
      <th><%= t "book" %></th>
      <th><%= t "action" %></th>
    </tr>
  </thead>
  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= link_to author.name, admin_author_path(author) %></td>
        <td><%= author.books.size %></td>
        <td>
          <div class="btn-group btn-group-sm">
            <%= link_to edit_admin_author_path(author) do %>
              <i class="glyphicon glyphicon-pencil btn btn-warning"
                title="<%= t "edit" %>"></i>
            <% end %>
            <%= link_to admin_author_path(author), method: :delete,
              data: {confirm: t("confirm")} do %>
              <i class="glyphicon glyphicon-trash btn btn-danger"
                title="<%= t "delete" %>"></i>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/authors/new.html.erb
<% provide :title, t(".create") %>
<h1 class="text-center"><%= t ".create" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @author] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, t(".description") %>
      <%= f.text_field :description, class: "form-control" %><br>

      <%= f.submit t(".create"), class: "btn btn-primary form-control" %>
    <% end %>
  </div>
</div>

app/views/admin/authors/show.html.erb
<% provide :title, @author.name %>
<div class="author">
  <h2><%= @author.name %></h2>
  <p><%= @author.description %></p>
  <ul>
    <% @books.each do |book| %>
      <li><%= book.name %></li>
    <% end %>
  </ul>
</div>