config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "pages/help", to: "pages#help"
  get "/pages/:page", to: "pages#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    resources :book_borrows, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end
  resources :books
  resources :authors, only: :show
  resources :relationships, only: [:create, :destroy]

  namespace :admin do
    root "book_borrows#index"
    resources :users
    resources :authors
    resources :books
    resources :publishers
    resources :categories
    resources :book_borrows, only: [:index, :update, :destroy]
  end
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books
  validates :name, presence: true, length: {maximum: Settings.name.maximum}
  validates :description, presence: true
  validates :address, presence: true
  scope :search, ->q{where "name LIKE ?", "%#{q}%"}
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :load_publisher, except: [:new, :index, :create]
  layout "admin"

  def index
    if params[:q].present?
      @publishers = Publisher.includes(:books).select(:id, :name, :address)
        .search(params[:q]).order(name: :asc).paginate page: params[:page],
        per_page: Settings.paginate.per_page
    else
      @publishers = Publisher.includes(:books).select(:id, :name, :address)
        .order(name: :asc).paginate page: params[:page],
        per_page: Settings.paginate.per_page
    end
  end

  def show
    @books = Book.where(publisher_id: @publisher.id)
  end

  def new
    @publisher = Publisher.new
  end

  def edit
  end

  def create
    @publisher = Publisher.new publisher_params
    if @publisher.save
      flash[:success] = t ".publisher"
      redirect_to admin_publishers_url
    else
      render :new
    end
  end

  def update
    if @publisher.update_attributes publisher_params
      flash[:success] = t ".success"
      redirect_to admin_publisher_url
    else
      render :edit
    end
  end

  def destroy
    if @publisher.books.any?
       flash[:danger] = t ".delete_fail"
    else
      if @publisher.destroy
        flash[:success] = t ".delete"
      else
        flash[:danger] = t ".delete_fail"
      end
    end
    redirect_to admin_publishers_url
  end

  private

  def publisher_params
    params.require(:publisher).permit :name, :description, :address
  end

  def load_publisher
    @publisher = Publisher.find_by id: params[:id]
    unless @publisher
      flash[:danger] = t ".none"
      redirect_to admin_publishers_url
    end
  end
end

app/views/admin/publishers/edit.html.erb
<% provide :title, t(".editpublisher") %>
<h1><%= t ".update" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @publisher] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, t(".description") %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.label :address, t(".address") %>
      <%= f.text_field :address, class: "form-control" %>

      <%= f.submit t(".update"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/publishers/index.html.erb
<% provide :title, t(".all_publisher") %>
<% provide :placeholder, t(".search_publisher") %>
<h1><%= t ".all_publisher" %> </h1>

<%= form_for admin_publishers_path, method: :get do %>
  <%= render "shared/search_form" %>
<% end %>

<%= will_paginate %>

<table class="table">
  <thead>
    <tr>
      <th><%= t "name" %></th>
      <th><%= t "address" %> </th>
      <th><%= t "book" %></th>
      <th><%= t "action" %></th>
    </tr>
  </thead>
  <tbody>
    <% @publishers.each do |publisher| %>
      <tr>
        <td><%= link_to publisher.name, admin_publisher_path(publisher) %></td>
        <td><%= publisher.address %></td>
        <td><%= publisher.books.size %></td>
        <td>
          <div class="btn-group btn-group-sm">
            <%= link_to edit_admin_publisher_path(publisher) do %>
              <i class="glyphicon glyphicon-pencil btn btn-warning"
                title="<%= t "edit" %>"></i>
            <% end %>
            <%= link_to admin_publisher_path(publisher), method: :delete,
              data: {confirm: t("confirm")} do %>
              <i class="glyphicon glyphicon-trash btn btn-danger"
                title="<%= t "delete" %>"></i>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/publishers/new.html.erb
<% provide :title, t(".create") %>
<h1 class="text-center"><%= t ".create" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @publisher] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, t(".description") %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.label :address, t(".address") %>
      <%= f.text_field :address, class: "form-control" %><br>

      <%= f.submit t(".create"), class: "btn btn-primary form-control" %>
    <% end %>
  </div>
</div>

app/views/admin/publishers/show.html.erb
<% provide :title, @publisher.name %>
<div class="publisher">
  <h2><%= @publisher.name %></h2>
  <p><%= @publisher.description %></p>
  <p><%= @publisher.address %></p>
  <ul>
    <% @books.each do |book| %>
      <li><%= book.name %></li>
    <% end %>
  </ul>
</div>