config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "pages/help", to: "pages#help"
  get "/pages/:page", to: "pages#show"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    resources :book_borrows, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end
  resources :books
  resources :authors, only: :show
  resources :relationships, only: [:create, :destroy]

  namespace :admin do
    root "book_borrows#index"
    resources :users
    resources :authors
    resources :books
    resources :publishers
    resources :categories
    resources :book_borrows, only: [:index, :update, :destroy]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
  validates :name, presence: true, length: {maximum: Settings.name.maximum}
  validates :description, presence: true
  scope :search, ->q{where "name LIKE ?", "%#{q}%"}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :load_category, except: [:new, :index, :create]
  layout "admin"

  def index
    if params[:q].present?
      @categories = Category.includes(:books).select(:id, :name)
        .search(params[:q]).order(name: :asc).paginate page: params[:page],
        per_page: Settings.paginate.per_page
    else
      @categories = Category.includes(:books).select(:id, :name)
        .order(name: :asc).paginate page: params[:page],
        per_page: Settings.paginate.per_page
    end
  end

  def show
    @books = Book.where(category_id: @category.id)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t ".category"
      redirect_to admin_categories_url
    else
      render :new
    end
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".success"
      redirect_to admin_categories_url
    else
      render :edit
    end
  end

  def destroy
    if @category.books.any?
       flash[:danger] = t ".delete_fail"
    else
      if @category.destroy
        flash[:success] = t ".delete"
      else
        flash[:danger] = t ".delete_fail"
      end
    end
    redirect_to admin_categories_url
  end

  private

  def category_params
    params.require(:category).permit :name, :description
  end

  def load_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t ".none"
      redirect_to admin_categories_url
    end
  end
end

app/views/admin/categories/edit.html.erb
<% provide :title, t(".editcategory") %>
<h1><%= t ".update" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, t(".description") %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.submit t(".update"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t(".all_category") %>
<% provide :placeholder, t(".search_category") %>
<h1><%= t ".all_category" %> </h1>

<%= form_for admin_categories_path, method: :get do %>
  <%= render "shared/search_form" %>
<% end %>

<%= will_paginate %>

<table class="table">
  <thead>
    <tr>
      <th><%= t "name" %></th>
      <th><%= t "book" %></th>
      <th><%= t "action" %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, admin_category_path(category) %></td>
        <td><%= category.books.size %></td>
        <td>
          <div class="btn-group btn-group-sm">
            <%= link_to edit_admin_category_path(category) do %>
              <i class="glyphicon glyphicon-pencil btn btn-warning"
                title="<%= t "edit" %>"></i>
            <% end %>
            <%= link_to admin_category_path(category), method: :delete,
              data: {confirm: t("confirm")} do %>
              <i class="glyphicon glyphicon-trash btn btn-danger"
                title="<%= t "delete" %>"></i>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/categories/new.html.erb
<% provide :title, t(".create") %>
<h1 class="text-center"><%= t ".create" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, t(".description") %>
      <%= f.text_field :description, class: "form-control" %><br>

      <%= f.submit t(".create"), class: "btn btn-primary form-control" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/show.html.erb
<% provide :title, @category.name %>
<div class="category">
  <h2><%= @category.name %></h2>
  <p><%= @category.description %></p>
  <ul>
    <% @books.each do |book| %>
      <li><%= book.name %></li>
    <% end %>
  </ul>
</div>